source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ARFormValidator_Example', :exclusive => true do
  pod "ARFormValidator", :path => "../"
end

target 'ARFormValidator_Tests', :exclusive => true do
  pod "ARFormValidator", :path => "../"

  
end
